CC = gcc

# all: main

# product: product.c
# 	$(CC) product.c -o product

# reader: reader.c
# 	$(CC) reader.c -o reader

# printer: printer.c
# 	$(CC) printer.c -o printer

# score: score.c
# 	$(CC) score.c -o score

# trie: trie.c
# 	$(CC) trie.c -o trie

main: main.c product.c reader.c printer.c score.c trie.c global.h
	$(CC) main.c -o main
