CC = gcc

all: main

films: films.c
	$(CC) films.c -o films

factorial: factorial.c
	$(CC) factorial.c -o factorial

sums: sums.c
	$(CC) sums.c -o sums

main: main.c films.c factorial.c sums.c
	$(CC) main.c -o main